<?php

// autoload_classmap.php @generated by Composer

$verificationDir = dirname(__DIR__);
$baseDir = dirname($verificationDir);

return array(
    'Composer\\InstalledVersions' => $verificationDir . '/composer/InstalledVersions.php',
);
