<?php

// autoload_psr4.php @generated by Composer

$verificationDir = dirname(__DIR__);
$baseDir = dirname($verificationDir);

return array(
    'PHPMailer\\PHPMailer\\' => array($verificationDir . '/phpmailer/phpmailer/src'),
);
